#!/bin/bash
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y git build-essential silversearcher-ag golang tree keychain zsh htop tmux zlib1g-dev exuberant-ctags mercurial jq mosh aspell glances p7zip-full
make force_emacs_install
# sudo apt-get install -y silversearcher-ag golang tree keychain zsh htop tmux python-software-properties zlib1g-dev exuberant-ctags mercurial jq mosh shellcheck
# sudo apt-get install -y emacs
# sudo apt-get install -y build-essential

# docker
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
sudo apt update
sudo apt-get install -y docker-ce

