#!/bin/zsh
setopt null_glob

cd ~/.config/dotfiles/zsh

for f in $(ls zshrc.d/* | grep '\.sh'); do
  # echo "loading $f"
  source $f
done

for f in $(ls zshenv-post.d/* | grep '\.sh'); do
  # echo "loading $f"
  source $f
done

