#!/bin/bash
apt install -y apt-transport-https ca-certificates curl software-properties-common
echo 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic edge' >> /etc/apt/sources.list.d/docker.list
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt update
apt install -y docker-ce
usermod -aG docker bmd
systemctl enable docker

