#!/bin/bash
# https://remysharp.com/2018/08/23/cli-improved

cd "$HOME/Downloads"

wget https://github.com/sharkdp/fd/releases/download/v7.1.0/fd-musl_7.1.0_amd64.deb
sudo dpkg -i fd-musl_7.1.0_amd64.deb

mkdir -p ~/bin
curl -o ~/bin/tldr https://raw.githubusercontent.com/raylee/tldr/master/tldr
chmod +x ~/bin/tldr
