(provide 'my-windows)

  (global-set-key (kbd "M-1") 'select-window-1)
  (global-set-key (kbd "M-2") 'select-window-2)
  (global-set-key (kbd "M-3") 'select-window-3)
  (global-set-key (kbd "M-4") 'select-window-4)
  (global-set-key (kbd "M-5") 'select-window-5)
  (global-set-key (kbd "M-6") 'select-window-6)
  (global-set-key (kbd "M-7") 'select-window-7)
  (global-set-key (kbd "M-8") 'select-window-8)
  (global-set-key (kbd "M-9") 'select-window-9)

  (global-set-key (kbd "M-l") 'evil-window-next)
  (global-set-key (kbd "M-h") 'evil-window-prev)
  (global-unset-key (kbd "M-j"))
  (global-set-key (kbd "M-j") 'evil-window-next)
  (global-set-key (kbd "M-k") 'evil-window-prev)

  ;; (define-key auto-highlight-symbol-mode-major-mode (kbd "M--") nil)
  ;; (local-unset-key "M--")
  ;; (global-unset-key (kbd "M--"))
  ;; (define-key minor-mode-map (kbd "M--") 'split-window-below-and-focus)
  ;; (define-key minor-mode-map (kbd "M-_") 'split-window-below-and-focus)
  ;; (global-set-key (kbd "M--") 'split-window-below-and-focus)
  ;; (local-set-key (kbd "M--") 'split-window-below-and-focus)
  ;; (global-set-key (kbd "M-_") 'split-window-below-and-focus)
  ;; (global-set-key (kbd "M-_") 'split-window-vertically)
  ;; (local-unset-key (kbd "M--"))
  ;; (local-unset-key "M--")
  ;; (local-unset-key "\M--")
  ;; (global-unset-key (kbd "M--"))
  (global-set-key (kbd "M--") 'split-window-below-and-focus)
  (global-set-key (kbd "M-\\") 'split-window-right-and-focus)
  (global-set-key (kbd "M-n") 'split-window-right-and-focus)
  (define-key (current-global-map) [remap ahs-back-to-start] 'split-window-below-and-focus)

  ;; these are M-left and M-right. These interfere with org mode
  ;; (define-key (current-global-map) [remap ahs-forward] 'evil-window-decrease-width)
  ;; (define-key (current-global-map) [remap ahs-backward] 'evil-window-increase-width)

  ;; (global-unset-key (kbd "M-<left>"))
  ;; (global-unset-key "\M-left")
  ;; (global-unset-key "\M-right")
  ;; (global-set-key (kbd "M-C-k") 'evil-window-decrease-height)
  ;; (global-set-key (kbd "M-C-j") 'evil-window-increase-height)
  ;; (global-set-key (kbd "M-C-h") 'evil-window-decrease-width)
  ;; (global-set-key (kbd "M-C-l") 'evil-window-increase-width)

  (global-set-key (kbd "C-M-=") 'default-text-scale-increase)
  (global-set-key (kbd "C-M--") 'default-text-scale-decrease)

