if [[ -d "$HOME/.config/dotfiles/zsh/zshenv.d" ]]; then
    for f in $HOME/.config/dotfiles/zsh/zshenv.d/*.sh; do
        # echo "loading zshenv-post.d: $f"
        source $f
    done
fi

#echo
#echo "done zshenv"
