#!/bin/zsh

setopt null_glob

if [[ -d "$HOME/.config/dotfiles/zsh/zshenv.d" ]]; then
  for f in $(ls "$HOME/.config/dotfiles/zsh/zshenv.d/*" | grep '\.sh'); do
      # echo "loading zshenv: $f"
      source $f
  done
fi
